ui: tape
browsers:
  - name: chrome
    version: latest
  - name: safari
    version: latest
  - name: firefox
    version: latest
  - name: ie
    version: 8..latest
  - name: iphone
    version: latest
  - name: android
    version: latest
builder: zuulnice
browserify:
    extensions:
      - .js
server: './tests/support/server.js'
