// Generated by CoffeeScript 1.6.3
(function() {
  var Postie, Writable,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Writable = require('readable-stream/writable');

  Postie = (function(_super) {
    __extends(Postie, _super);

    function Postie(channel, target, targetOrigin) {
      this.channel = channel;
      this.target = target;
      this.targetOrigin = targetOrigin != null ? targetOrigin : '*';
      Postie.__super__.constructor.call(this, {
        decodeStrings: false,
        objectMode: true
      });
    }

    Postie.prototype._write = function(chunk, encoding, next) {
      var pkg;
      pkg = JSON.stringify({
        _postie: {
          channel: this.channel,
          "package": chunk
        }
      });
      window.postMessage(this.target, pkg, this.targetOrigin);
      return next();
    };

    return Postie;

  })(Writable);

  module.exports = Postie;

}).call(this);
