// Generated by CoffeeScript 1.6.3
(function() {
  var Postie, Writable,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Writable = require('readable-stream').Writable;

  Postie = (function(_super) {
    __extends(Postie, _super);

    function Postie(name, target, targetOrigin) {
      this.name = name;
      this.target = target;
      this.targetOrigin = targetOrigin;
      if (!this.targetOrigin) {
        this.targetOrigin = '*';
      }
      Postie.__super__.constructor.call(this, {
        decodeStrings: false,
        objectMode: true
      });
    }

    Postie.prototype._write = function(chunk, encoding, next) {
      var pkg;
      console.log('_write');
      pkg = JSON.stringify({
        name: this.name,
        message: chunk
      });
      window.postMessage(pkg, this.target, this.targetOrigin);
      return next();
    };

    Postie.prototype.post = function(thing) {
      return this.write(thing);
    };

    return Postie;

  })(Writable);

  module.exports = Postie;

}).call(this);
